# Generated by Django 5.1.6 on 2025-02-15 11:36

import app.models.managers.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=255, null=True, verbose_name='name')),
                ('identification', models.CharField(max_length=15, unique=True, verbose_name='identification')),
                ('address', models.CharField(help_text='Direccion', max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(help_text='Numero de telefono', max_length=255, null=True, verbose_name='phone')),
                ('email', models.EmailField(help_text='Correo electronico', max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del método de pago', max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del método de pago', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el método de pago está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
                'db_table': 'payment_methods',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Username', max_length=255, unique=True, verbose_name='username')),
                ('name', models.CharField(help_text='Nombre', max_length=255, verbose_name='name')),
                ('lastname', models.CharField(help_text='Apellido', max_length=255, null=True, verbose_name='lastname')),
                ('identification', models.CharField(max_length=15, unique=True, verbose_name='identification')),
                ('phone', models.CharField(help_text='Numero de telefono', max_length=255, null=True, verbose_name='phone')),
                ('email', models.EmailField(help_text='Correo electronico', max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ('-id',),
            },
            managers=[
                ('objects', app.models.managers.user.UserManager()),
            ],
        ),
    ]
