# Generated by Django 5.1.6 on 2025-02-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proveedor', max_length=255, verbose_name='proveedores')),
                ('email', models.EmailField(help_text='Correo electrónico del proveedor', max_length=255, verbose_name='Correo electrónico')),
                ('phone', models.CharField(help_text='Teléfono del proveedor', max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el método de pago está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'suppilers',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la categoría', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activa')),
                ('parent_id', models.ForeignKey(blank=True, help_text='Categoría superior en la jerarquía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_category_name_per_parent')],
            },
        ),
    ]
