# Generated by Django 5.1.6 on 2025-02-16 22:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de identificación', max_length=50, verbose_name='Tipo de identificación')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de transacción de inventario',
                'verbose_name_plural': 'Tipos de transacciones de inventario',
                'db_table': 'transaction_type_inventory',
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transaction_detail',
            field=models.CharField(blank=True, help_text='Referencia o número de la transacción', max_length=255, verbose_name='Detalles de la transaccion'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Cantidad de productos', verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='HistoricalInventory',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos', verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('X', 'Cancelado')], help_text='Estado de la transacción', max_length=1, verbose_name='Estado')),
                ('transaction_detail', models.CharField(blank=True, help_text='Referencia o número de la transacción', max_length=255, verbose_name='Detalles de la transaccion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_value', models.ForeignKey(blank=True, db_constraint=False, help_text='Valor del producto relacionado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.productvalue', verbose_name='Valor del Producto')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario que realizó la transacción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('transaction_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de transaccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.transactiontypeinventory', verbose_name='Tipo de transaccion')),
            ],
            options={
                'verbose_name': 'historical Inventario',
                'verbose_name_plural': 'historical Inventarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='transaction_type',
            field=models.ForeignKey(help_text='Tipo de transaccion', on_delete=django.db.models.deletion.CASCADE, to='app.transactiontypeinventory', verbose_name='Tipo de transaccion'),
        ),
    ]
