# Generated by Django 5.1.6 on 2025-02-16 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suppiler_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Categoría')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.suppiler', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Fecha de la venta', verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=10, verbose_name='Total')),
                ('client', models.ForeignKey(help_text='Cliente asociado a la venta', on_delete=django.db.models.deletion.CASCADE, to='app.client', verbose_name='Cliente')),
                ('payment_method', models.ForeignKey(help_text='Método de pago utilizado', on_delete=django.db.models.deletion.CASCADE, to='app.paymentmethod', verbose_name='Método de pago')),
                ('seller', models.ForeignKey(help_text='Usuario que realizó la venta', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales',
                'ordering': ('-date',),
            },
        ),
    ]
