# Generated by Django 5.1.6 on 2025-02-16 23:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transactiontypeinventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Supplier', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=255, verbose_name='name')),
                ('lastname', models.CharField(help_text='Apellido del cliente', max_length=255, verbose_name='name')),
                ('identification', models.CharField(db_index=True, max_length=15, verbose_name='identification')),
                ('address', models.CharField(help_text='Direccion', max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(help_text='Numero de telefono', max_length=255, null=True, verbose_name='phone')),
                ('email', models.EmailField(db_index=True, help_text='Correo electronico', max_length=255, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identification_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de identificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.identificationtype', verbose_name='identification type')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSaleDetail',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos vendidos', verbose_name='Cantidad')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_value_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Valor del producto en el momento de la venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.productvalue', verbose_name='Valor del Producto')),
                ('sale_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Venta asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.sales', verbose_name='Venta')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Detalle de Venta',
                'verbose_name_plural': 'historical Detalles de Venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
