# Generated by Django 5.1.6 on 2025-02-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo del producto', max_digits=10, verbose_name='Costo')),
                ('product_id', models.ForeignKey(help_text='Producto asociado a este valor', on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Valor del Producto',
                'verbose_name_plural': 'Valores de Productos',
                'db_table': 'product_values',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad de productos vendidos', verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, verbose_name='Precio Unitario')),
                ('product_value_id', models.ForeignKey(help_text='Valor del producto en el momento de la venta', on_delete=django.db.models.deletion.CASCADE, to='app.productvalue', verbose_name='Valor del Producto')),
                ('sale_id', models.ForeignKey(help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, to='app.sales', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'sale_details',
            },
        ),
    ]
