# Generated by Django 5.1.6 on 2025-02-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_supplier_remove_saledetail_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
