# Generated by Django 5.1.6 on 2025-02-16 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productvalue_saledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Cantidad de productos', verbose_name='Cantidad')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('X', 'Cancelado')], help_text='Estado de la transacción', max_length=1, verbose_name='Estado')),
                ('transaction_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], help_text='Tipo de transacción (Entrada/Salida)', max_length=3, verbose_name='Tipo de Transacción')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de la transacción', verbose_name='Fecha de Transacción')),
                ('transaction_reference', models.CharField(help_text='Referencia o número de la transacción', max_length=255, verbose_name='Referencia de Transacción')),
                ('product_value', models.ForeignKey(help_text='Valor del producto relacionado', on_delete=django.db.models.deletion.CASCADE, to='app.productvalue', verbose_name='Valor del Producto')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la transacción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventory',
            },
        ),
    ]
