# Generated by Django 5.1.6 on 2025-02-19 00:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achronym', models.CharField(help_text='Acronimo del banco', max_length=10, null=True, unique=True)),
                ('code', models.CharField(db_column='code', help_text='Codigo del banco', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre del banco', max_length=100)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencys',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(help_text='Moneda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dollar_rate', to='app.currency')),
            ],
            options={
                'verbose_name': 'currency rate',
                'verbose_name_plural': 'currency rate',
                'db_table': 'currency_rate',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=8)),
                ('date', models.DateTimeField(help_text='Fecha en la que se registro el pago')),
                ('description', models.TextField(blank=True, help_text='motivo/descripcion del pago')),
                ('reference', models.CharField(help_text='referencia de pagomovil/transferencia', max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_destiny', models.ForeignKey(blank=True, db_constraint=False, help_text='Banco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.bank')),
                ('bank_origin', models.ForeignKey(blank=True, db_constraint=False, help_text='Banco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.bank')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, db_constraint=False, help_text='Método de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical payment',
                'verbose_name_plural': 'historical payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=8)),
                ('date', models.DateTimeField(help_text='Fecha en la que se registro el pago')),
                ('description', models.TextField(blank=True, help_text='motivo/descripcion del pago')),
                ('reference', models.CharField(help_text='referencia de pagomovil/transferencia', max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('bank_destiny', models.ForeignKey(help_text='Banco', on_delete=django.db.models.deletion.CASCADE, related_name='distiny_payments', to='app.bank')),
                ('bank_origin', models.ForeignKey(help_text='Banco', on_delete=django.db.models.deletion.CASCADE, related_name='origin_payments', to='app.bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(help_text='Método de pago', on_delete=django.db.models.deletion.CASCADE, related_name='payment_company', to='app.paymentmethod')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_company',
                'ordering': ('-id',),
                'unique_together': {('method', 'bank_destiny', 'reference', 'status')},
            },
        ),
    ]
