# Generated by Django 5.1.6 on 2025-02-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bank_currency_currencyrate_historicalpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(default=1, help_text='Moneda', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='app.currency'),
            preserve_default=False,
        ),
    ]
