# Generated by Django 5.1.6 on 2025-02-19 01:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paymentmethod_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentSaleDetail',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, help_text='pago ligado a la factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.payment')),
                ('sale_detail', models.ForeignKey(blank=True, db_constraint=False, help_text='Id Factura del contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.saledetail')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Payment Sale Detail',
                'verbose_name_plural': 'historical Payment Sale Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentSaleDetail',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='pago ligado a la factura', on_delete=django.db.models.deletion.CASCADE, related_name='payment_sale_detail', to='app.payment')),
                ('sale_detail', models.ForeignKey(help_text='Id Factura del contrato', on_delete=django.db.models.deletion.CASCADE, related_name='payment_sale_detail', to='app.saledetail')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Sale Detail',
                'verbose_name_plural': 'Payment Sale Details',
                'db_table': 'payments_sale_details',
                'ordering': ('-id',),
            },
        ),
    ]
