# Generated by Django 5.1.6 on 2025-02-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_historicalproduct_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
    ]
