# Generated by Django 5.1.6 on 2025-02-19 01:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_category_historicalproduct_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True),
        ),
        migrations.AddField(
            model_name='productvalue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True),
        ),
        migrations.AddField(
            model_name='productvalue',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productvalue',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvalue',
            name='product_id',
            field=models.ForeignKey(help_text='Producto asociado a este valor', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='HistoricalProductValue',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Costo del producto', max_digits=10, verbose_name='Costo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Producto asociado a este valor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Valor del Producto',
                'verbose_name_plural': 'historical Valores de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
