# Generated by Django 5.1.6 on 2025-02-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_productvalue_created_at_productvalue_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproductvalue',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='historicalsaledetail',
            old_name='product_value_id',
            new_name='product_value',
        ),
        migrations.RenameField(
            model_name='historicalsaledetail',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='productvalue',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='product_value_id',
            new_name='product_value',
        ),
        migrations.RenameField(
            model_name='saledetail',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
