# Generated by Django 5.1.6 on 2025-02-23 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transactiontypeinventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaledetail',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Valor del producto en el momento de la venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.inventory', verbose_name='Valor del Producto'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='inventory',
            field=models.ForeignKey(default=1, help_text='Valor del producto en el momento de la venta', on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='app.inventory', verbose_name='Valor del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product_value',
            field=models.ForeignKey(help_text='Valor del producto en el momento de la venta', on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='app.productvalue', verbose_name='Valor del Producto'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='app.sales', verbose_name='Venta'),
        ),
    ]
