# Generated by Django 5.1.6 on 2025-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_historicalsaledetail_inventory_saledetail_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado de la transacción', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado de la transacción', max_length=1, verbose_name='Estado'),
        ),
    ]
