# Generated by Django 5.1.6 on 2025-02-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_historicalproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
