# Generated by Django 5.1.6 on 2025-02-24 15:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-created_at',), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='seller',
        ),
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='currency_rate',
            field=models.ForeignKey(default=1, help_text='Currency Rate', on_delete=django.db.models.deletion.CASCADE, to='app.currencyrate', verbose_name='Currency Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricalSales',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente asociado a la venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency_rate', models.ForeignKey(blank=True, db_constraint=False, help_text='Currency Rate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.currencyrate', verbose_name='Currency Rate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
