# Generated by Django 5.1.6 on 2025-02-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_sales_options_remove_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-created_at',), 'permissions': (('list_sales', 'Can list Sales'),), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='is_active',
        ),
    ]
