# Generated by Django 5.1.6 on 2025-02-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_sales_options_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together={('currency', 'date')},
        ),
    ]
