# Generated by Django 5.1.6 on 2025-02-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_currencyrate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='currency_rate',
            field=models.ForeignKey(help_text='Currency Rate', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.currencyrate', verbose_name='Currency Rate'),
        ),
    ]
